import { Dimensions, Platform, StyleSheet } from "react-native";

const { width } = Dimensions.get("window");
export const bookdetailstyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f5f5f5",
  },
  contentContainer: {
    padding: 15,
    paddingBottom: 30,
  },
  topBar: {
    backgroundColor: "#2c3e50",
    paddingTop: Platform.OS === "ios" ? 40 : 10,
  },
  backButton: {
    flexDirection: "row",
    alignItems: "center",
    padding: 10,
  },
  backText: {
    color: "white",
    marginLeft: 10,
    fontSize: 16,
    fontWeight: "500",
  },
  card: {
    flexDirection: "row",
    backgroundColor: "white",
    borderRadius: 10,
    padding: 15,
    marginTop: 10,
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  bookCover: {
    width: width * 0.3,
    height: width * 0.45,
    borderRadius: 8,
  },
  details: {
    flex: 1,
    marginLeft: 15,
    position: "relative",
  },
  title: {
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 5,
  },
  author: {
    fontSize: 16,
    color: "#555",
    marginBottom: 5,
  },
  category: {
    fontSize: 14,
    color: "#777",
    marginBottom: 10,
  },
  description: {
    fontSize: 14,
    color: "#333",
    lineHeight: 20,
  },
  readMoreButton: {
    marginTop: 5,
    alignSelf: "flex-start",
  },
  readMoreText: {
    color: "#3498db",
    fontWeight: "600",
  },
  favoriteButton: {
    position: "absolute",
    top: 0,
    right: 0,
    padding: 5,
  },
  progressContainer: {
    marginTop: 20,
    backgroundColor: "white",
    borderRadius: 10,
    padding: 15,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
  },
  progressTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 10,
  },
  progressBar: {
    width: "100%",
  },
  progressText: {
    marginTop: 5,
    fontSize: 14,
    color: "#666",
    textAlign: "right",
  },
  chapterListContainer: {
    marginTop: 20,
    backgroundColor: "white",
    borderRadius: 10,
    padding: 15,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
  },
  commentSection: {
    marginTop: 5,
    backgroundColor: "#fff",
    borderRadius: 10,
    padding: 10,
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  commentTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#e0e0e0",
    paddingBottom: 10,
  },
  comment: {
    padding: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
    marginBottom: 5,
  },
  noComments: {
    fontStyle: "italic",
    color: "#888",
    textAlign: "center",
    padding: 20,
  },
  commentInputContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 15,
    borderTopWidth: 1,
    borderTopColor: "#f0f0f0",
    paddingTop: 15,
  },
  commentInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#ddd",
    padding: 10,
    borderRadius: 20,
    maxHeight: 100,
    backgroundColor: "#f9f9f9",
  },
  postButton: {
    backgroundColor: "#3498db",
    paddingVertical: 10,
    paddingHorizontal: 15,
    marginLeft: 10,
    borderRadius: 20,
  },
  postButtonText: {
    color: "white",
    fontWeight: "bold",
  },
  commentInputContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 15,
    backgroundColor: "#f9f9f9",
    borderRadius: 20,
    padding: 10,
    borderWidth: 1,
    borderColor: "#ddd",
  },
  commentInput: {
    flex: 1,
    fontSize: 16,
    color: "#333",
    paddingVertical: 8,
    paddingHorizontal: 12,
    maxHeight: 100,
    textAlignVertical: "top", // Ensure text starts at the top for multiline
  },
  postButton: {
    backgroundColor: "#3498db",
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  postButtonText: {
    color: "white",
    fontWeight: "600",
    fontSize: 14,
  },
  loginPrompt: {
    fontSize: 14,
    color: "#888",
    textAlign: "center",
    marginBottom: 15,
  },
});
