import { StyleSheet } from "react-native";

export const bookmanagestyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f8f9fd", // Lighter background for modern feel
  },
  titleContainer: {
    padding: 20,
    backgroundColor: "#ffffff",
    borderBottomWidth: 1,
    borderBottomColor: "#e8eaf6",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 3,
  },
  screenTitle: {
    fontSize: 24,
    fontWeight: "700",
    color: "#3a3a3a",
    letterSpacing: 0.5,
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderRadius: 12,
    margin: 16,
    paddingHorizontal: 16,
    paddingVertical: 8,
    shadowColor: "#5d7bff",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  searchIcon: {
    marginRight: 10,
    color: "#5d7bff",
  },
  searchInput: {
    flex: 1,
    height: 44,
    fontSize: 16,
    color: "#3a3a3a",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingBottom: 12,
    marginTop: 4,
  },
  headerTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#666",
    marginRight: 10,
  },
  sortButton: {
    marginHorizontal: 6,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: "#f2f4ff",
    borderWidth: 1,
    borderColor: "#eceef9",
  },
  activeSortButton: {
    backgroundColor: "#5d7bff",
    borderColor: "#5d7bff",
  },
  sortButtonText: {
    fontSize: 14,
    color: "#666",
    fontWeight: "500",
  },
  activeSortText: {
    color: "#fff",
    fontWeight: "600",
  },
  listContainer: {
    padding: 16,
    paddingTop: 8,
  },
  bookItem: {
    flexDirection: "row",
    backgroundColor: "#fff",
    borderRadius: 16,
    marginBottom: 16,
    padding: 16,
    shadowColor: "#5d7bff",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
    borderWidth: 1,
    borderColor: "#f0f2ff",
  },
  bookImage: {
    width: 90,
    height: 135,
    borderRadius: 10,
    marginRight: 16,
  },
  bookInfo: {
    flex: 1,
    justifyContent: "space-between",
  },
  bookTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#3a3a3a",
    marginBottom: 6,
    lineHeight: 22,
  },
  bookAuthor: {
    fontSize: 15,
    color: "#666",
    marginBottom: 6,
    fontWeight: "500",
  },
  bookCategory: {
    fontSize: 13,
    color: "#5d7bff",
    backgroundColor: "#f2f4ff",
    alignSelf: "flex-start",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    marginBottom: 10,
    fontWeight: "600",
  },
  bookDetails: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 8,
  },
  bookPrice: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#5d7bff",
  },
  bookStock: {
    fontSize: 14,
    color: "#888",
  },
  actionButtons: {
    justifyContent: "space-around",
    padding: 8,
  },
  editButton: {
    marginBottom: 16,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#f2f4ff",
    alignItems: "center",
    justifyContent: "center",
  },
  deleteButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#ffefef",
    alignItems: "center",
    justifyContent: "center",
  },
  addButton: {
    position: "absolute",
    bottom: 24,
    right: 24,
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "#5d7bff",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#5d7bff",
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  emptyContainer: {
    alignItems: "center",
    justifyContent: "center",
    padding: 40,
    marginTop: 40,
  },
  emptyText: {
    fontSize: 17,
    color: "#888",
    marginTop: 16,
    fontWeight: "500",
  },
  loader: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  modalContent: {
    width: "90%",
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 10,
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: "bold",
    marginBottom: 24,
    textAlign: "center",
    color: "#3a3a3a",
  },
  inputGroup: {
    marginBottom: 20,
  },
  inputLabel: {
    fontSize: 16,
    marginBottom: 8,
    color: "#555",
    fontWeight: "600",
  },
  textInput: {
    borderWidth: 1,
    borderColor: "#e8eaf6",
    borderRadius: 12,
    padding: 14,
    fontSize: 16,
    backgroundColor: "#f8f9fd",
  },
  rowInputs: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  modalButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 30,
  },
  modalButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  cancelButton: {
    backgroundColor: "#f2f4ff",
    marginRight: 12,
  },
  saveButton: {
    backgroundColor: "#5d7bff",
  },
  cancelButtonText: {
    fontSize: 16,
    color: "#5d7bff",
    fontWeight: "600",
  },
  saveButtonText: {
    fontSize: 16,
    color: "#fff",
    fontWeight: "600",
  },
  statsContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  statItem: {
    marginRight: 12,
    fontSize: 14,
    color: "#666",
    fontWeight: "500",
  },
  chaptersInfo: {
    fontSize: 14,
    color: "#555",
    marginTop: 6,
    fontWeight: "500",
  },
  bookStatus: {
    fontSize: 14,
    color: "#555",
    fontWeight: "500",
    backgroundColor: "#f8f9fd",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
  },
  textAreaInput: {
    height: 120,
    textAlignVertical: "top",
    paddingTop: 14,
  },
});
